import "@/lib/env" // validate env at boot — throws immediately on malformed values
import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import { QueryClientProvider } from "@tanstack/react-query"
import { HelmetProvider } from "react-helmet-async"
import { queryClient } from "@/lib/query-client"
import * as Sentry from "@sentry/react"
import { env } from "@/lib/env"
import { setupGlobalErrorHandlers } from "@/lib/error-utils"
import { ThemeProvider } from "@/contexts/theme-context"
import { WalletProvider } from "@/hooks/use-wallet"
import "./index.css"
import App from "./App.tsx"

// ─── Sentry Error Tracking ────────────────────────────────────────────────────

if (env.VITE_SENTRY_DSN) {
  Sentry.init({
    dsn: env.VITE_SENTRY_DSN,
    integrations: [Sentry.browserTracingIntegration(), Sentry.replayIntegration()],
    // Tracing
    tracesSampleRate: 1.0, // Capture 100% of transactions in dev/production
    // Session Replay
    replaysSessionSampleRate: 0.1, // Sample 10% of sessions
    replaysOnErrorSampleRate: 1.0, // Sample 100% of sessions where an error occurs
  })
}

// Register global error/rejection handlers after Sentry is initialised so
// unhandled promise rejections are forwarded with correct Sentry context.
setupGlobalErrorHandlers()

if (import.meta.env.DEV) {
  Promise.all([import("@axe-core/react"), import("react"), import("react-dom")]).then(
    ([axe, React, ReactDOM]) => {
      axe.default(React.default, ReactDOM.default, 1000)
    }
  )
} else {
  // Register the Workbox service worker generated by vite-plugin-pwa.
  // `registerSW` is a virtual module injected at build time.
  import("virtual:pwa-register").then(({ registerSW }) => {
    registerSW({
      // Silently pre-cache the new SW; next reload will pick up the update.
      onRegisteredSW(swUrl, r) {
        if (import.meta.env.DEV) console.info("[SW] registered at", swUrl, r)
      },
      onOfflineReady() {
        if (import.meta.env.DEV) console.info("[SW] app ready to work offline")
      },
    })
  })
}

// ─── Vercel Analytics ─────────────────────────────────────────────────────────
//
// inject() loads an external script (~1 kB) that would otherwise compete with
// first-paint resources if called at module-evaluation time.
//
// Strategy: defer until the browser is idle (requestIdleCallback), falling back
// to a 0 ms setTimeout in environments that don't support rIC (e.g. Safari < 16).
// Either path fires well after the first meaningful paint, leaving LCP unaffected.
//
// Note: we only call inject() in production — analytics in dev creates noise.

if (import.meta.env.PROD) {
  const scheduleAnalytics = () => {
    import("@vercel/analytics").then(({ inject }) => inject())
  }

  if (typeof requestIdleCallback !== "undefined") {
    requestIdleCallback(scheduleAnalytics)
  } else {
    // Safari / older browsers: setTimeout(fn, 0) defers past the current task
    // and any pending microtasks, including React's render flush.
    setTimeout(scheduleAnalytics, 0)
  }
}

// ─── React Root ───────────────────────────────────────────────────────────────

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <HelmetProvider>
        <ThemeProvider>
          <WalletProvider>
            <App />
          </WalletProvider>
        </ThemeProvider>
      </HelmetProvider>
    </QueryClientProvider>
  </StrictMode>
)
