import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import { QueryClientProvider } from "@tanstack/react-query"
import { HelmetProvider } from "react-helmet-async"
import { queryClient } from "@/lib/query-client"
import "./index.css"
import App from "./App.tsx"

if (import.meta.env.DEV) {
  Promise.all([import("@axe-core/react"), import("react"), import("react-dom")]).then(
    ([axe, React, ReactDOM]) => {
      axe.default(React.default, ReactDOM.default, 1000)
    }
  )
} else {
  // Register the Workbox service worker generated by vite-plugin-pwa.
  // `registerSW` is a virtual module injected at build time.
  import("virtual:pwa-register").then(({ registerSW }) => {
    registerSW({
      // Silently pre-cache the new SW; next reload will pick up the update.
      onRegisteredSW(swUrl, r) {
        if (import.meta.env.DEV) console.info("[SW] registered at", swUrl, r)
      },
      onOfflineReady() {
        if (import.meta.env.DEV) console.info("[SW] app ready to work offline")
      },
    })
  })
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <HelmetProvider>
        <App />
      </HelmetProvider>
    </QueryClientProvider>
  </StrictMode>
)
